# Generated by Django 4.0.3 on 2022-04-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_delete_somemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='for_anonymos_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
    ]
